In [83]:
import numpy as np

In [8]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b=np.array([1,2,5,8,90])
b

array([ 1,  2,  5,  8, 90])

In [10]:
b[4]

90

In [11]:
b[2]=20
b

array([ 1,  2, 20,  8, 90])

In [12]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a[:,2]

array([3, 6, 9])

In [20]:
a[2,1]

8

In [21]:
a[1,:]

array([4, 5, 6])

In [22]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [23]:
a+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [25]:
a[:,[1,2]]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [27]:
z=np.random.randint(20, size=(4,5))
z

array([[19,  4, 17, 12,  6],
       [13,  0,  6,  3,  6],
       [ 8, 11, 10,  1,  8],
       [ 7,  9, 16,  6, 18]])

In [30]:
z*2

array([[38,  8, 34, 24, 12],
       [26,  0, 12,  6, 12],
       [16, 22, 20,  2, 16],
       [14, 18, 32, 12, 36]])

In [31]:
import pandas as pd

In [35]:
pd.Series([1,2,3,7])

0    1
1    2
2    3
3    7
dtype: int64

In [42]:
a=pd.Series([1,5,7,6,45,785,10,1,270,0])
a

0      1
1      5
2      7
3      6
4     45
5    785
6     10
7      1
8    270
9      0
dtype: int64

In [43]:
a.head(5)

0     1
1     5
2     7
3     6
4    45
dtype: int64

In [47]:
p=pd.Series([1,5,7,6,45,785,10,1,270,0],index=(9,8,7,6,5,4,3,2,1,0))
p

9      1
8      5
7      7
6      6
5     45
4    785
3     10
2      1
1    270
0      0
dtype: int64

In [48]:
sozluk={"log":11 , "reg":20, "cart":10}
sozluk

{'log': 11, 'reg': 20, 'cart': 10}

In [49]:
seri=pd.Series(sozluk)
seri

log     11
reg     20
cart    10
dtype: int64

In [123]:
yas={"aysun":20, "baris":21, "suna":22, "leyla":24}
bilgi=pd.Series(yas)
bilgi

aysun    20
baris    21
suna     22
leyla    24
dtype: int64

In [59]:
bilgi[1]

21

In [61]:
bilgi.keys

<bound method Series.keys of aysun    20
baris    21
suna     22
leyla    24
dtype: int64>

In [63]:
list(bilgi.items())

[('aysun', 20), ('baris', 21), ('suna', 22), ('leyla', 24)]

In [65]:
bilgi[["aysun"]]

aysun    20
dtype: int64

In [124]:
bilgi[["aysun","baris"]]

aysun    20
baris    21
dtype: int64

In [125]:
 pd.DataFrame(bilgi, columns=["Yas"])

Yas
aysun   20
baris   21
suna    22
leyla   24

In [89]:
import numpy as np
m=np.arange(1,10).reshape(3,3)

In [90]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
df = pd.DataFrame(m, columns = ["var", "var2", "var3"])

In [95]:
df

var  var2  var3
0    1     2     3
1    4     5     6
2    7     8     9

In [96]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['var', 'var2', 'var3'], dtype='object')]

In [97]:
bilgi

aysun    20
baris    21
suna     22
leyla    24
dtype: int64

In [103]:
a=np.arange(1,10).reshape(3,3)
z= pd.DataFrame(a, columns =["yas","dogum_tarihi","kan_grubu"])

In [104]:
z

yas  dogum_tarihi  kan_grubu
0    1             2          3
1    4             5          6
2    7             8          9

In [115]:
df1=pd.DataFrame({"isim":["aysun","baris","suna","leyla"],
                 "yas":[20,21,22,24]})
df1

isim  yas
0  aysun   20
1  baris   21
2   suna   22
3  leyla   24

In [119]:
df1["isim"]

0    aysun
1    baris
2     suna
3    leyla
Name: isim, dtype: object

In [125]:
df1["isim"][0:2]

0    aysun
1    baris
Name: isim, dtype: object

**  **

In [1]:
import numpy as np
import pandas as pd

In [162]:
neftlix=pd.DataFrame({"Yönetmen":["Davit Yarovesky" ,"Anthony Russo" ,"Özgür Bakar" ,"Chris Williams" ,"Daniel Roby", "Kristoffer Rus" , 
                                  "Alejandro Montiel" , "Onur Bilgetay", "Deon Taylor","Carrie Cracknell"],
                      "Film Adı":["Brightburn","The Gary Man" , "Hep Yek 4", "Deniz Canavarı","Bir Numaralı Hedef","Masal Bitti,Ben Büyüdüm" , "Pıpa",
                             "Aykut Enişte 2","Çürük Elma","İkna"],
                      "Yıl":[2019,2022,2021,2022,2020,2022,2022,2021,2019,2022],
                      "Süre":["1 sa. 30 dk" , "2 sa. 9 dk", "1 sa. 54 dk" , "1 sa. 59 dk" ,"2 sa. 5 dk" ,"1 sa. 46 dk" , "1 sa.56 dk", "1 sa. 58 dk",
                             "1 sa. 47 dk","1 sa. 49 dk"],
                      "Tür":["Bilim Kurgu","Kitaplardan uyarlanan", "Komedi","Aile" ,"Gerilim","Komedi,Aile" ,"Gerilim,Drama","Komedi", "Aksiyon ve Macera",
                            "Romantik Komedi"],
                      "Yetişkinlik Düzeyi":["18 +","16 +","16 +","7 +","18 +","7 +","16 +","13 +","18 +","7 +"],
                      "İzlenme Sayısı":[500000 ,780999 ,1000250 ,25544870,100000000 ,850451 ,999451 ,
                                        657998 ,2850000,1452888]})
neftlix

Yönetmen                 Film Adı   Yıl         Süre  \
0    Davit Yarovesky               Brightburn  2019  1 sa. 30 dk   
1      Anthony Russo             The Gary Man  2022   2 sa. 9 dk   
2        Özgür Bakar                Hep Yek 4  2021  1 sa. 54 dk   
3     Chris Williams           Deniz Canavarı  2022  1 sa. 59 dk   
4        Daniel Roby       Bir Numaralı Hedef  2020   2 sa. 5 dk   
5     Kristoffer Rus  Masal Bitti,Ben Büyüdüm  2022  1 sa. 46 dk   
6  Alejandro Montiel                     Pıpa  2022   1 sa.56 dk   
7      Onur Bilgetay           Aykut Enişte 2  2021  1 sa. 58 dk   
8        Deon Taylor               Çürük Elma  2019  1 sa. 47 dk   
9   Carrie Cracknell                     İkna  2022  1 sa. 49 dk   

                     Tür Yetişkinlik Düzeyi  İzlenme Sayısı  
0            Bilim Kurgu               18 +          500000  
1  Kitaplardan uyarlanan               16 +          780999  
2                 Komedi               16 +         1000250  
3                   Aile                7 +        25544870  
4                Gerilim               18 +       100000000  
5            Komedi,Aile                7 +          850451  
6          Gerilim,Drama               16 +          999451  
7                 Komedi               13 +          657998  
8      Aksiyon ve Macera               18 +         2850000  
9        Romantik Komedi                7 +         1452888

In [163]:
neftlix.groupby("Süre").min()

Yönetmen                 Film Adı   Yıl  \
Süre                                                            
1 sa. 30 dk    Davit Yarovesky               Brightburn  2019   
1 sa. 46 dk     Kristoffer Rus  Masal Bitti,Ben Büyüdüm  2022   
1 sa. 47 dk        Deon Taylor               Çürük Elma  2019   
1 sa. 49 dk   Carrie Cracknell                     İkna  2022   
1 sa. 54 dk        Özgür Bakar                Hep Yek 4  2021   
1 sa. 58 dk      Onur Bilgetay           Aykut Enişte 2  2021   
1 sa. 59 dk     Chris Williams           Deniz Canavarı  2022   
1 sa.56 dk   Alejandro Montiel                     Pıpa  2022   
2 sa. 5 dk         Daniel Roby       Bir Numaralı Hedef  2020   
2 sa. 9 dk       Anthony Russo             The Gary Man  2022   

                               Tür Yetişkinlik Düzeyi  İzlenme Sayısı  
Süre                                                                   
1 sa. 30 dk            Bilim Kurgu               18 +          500000  
1 sa. 46 dk            Komedi,Aile                7 +          850451  
1 sa. 47 dk      Aksiyon ve Macera               18 +         2850000  
1 sa. 49 dk        Romantik Komedi                7 +         1452888  
1 sa. 54 dk                 Komedi               16 +         1000250  
1 sa. 58 dk                 Komedi               13 +          657998  
1 sa. 59 dk                   Aile                7 +        25544870  
1 sa.56 dk           Gerilim,Drama               16 +          999451  
2 sa. 5 dk                 Gerilim               18 +       100000000  
2 sa. 9 dk   Kitaplardan uyarlanan               16 +          780999

In [164]:
neftlix.groupby("Yetişkinlik Düzeyi").count()

Yönetmen  Film Adı  Yıl  Süre  Tür  İzlenme Sayısı
Yetişkinlik Düzeyi                                                    
13 +                       1         1    1     1    1               1
16 +                       3         3    3     3    3               3
18 +                       3         3    3     3    3               3
7 +                        3         3    3     3    3               3

In [165]:
neftlix[(neftlix.Yıl < 2021)]

Yönetmen            Film Adı   Yıl         Süre                Tür  \
0  Davit Yarovesky          Brightburn  2019  1 sa. 30 dk        Bilim Kurgu   
4      Daniel Roby  Bir Numaralı Hedef  2020   2 sa. 5 dk            Gerilim   
8      Deon Taylor          Çürük Elma  2019  1 sa. 47 dk  Aksiyon ve Macera   

  Yetişkinlik Düzeyi  İzlenme Sayısı  
0               18 +          500000  
4               18 +       100000000  
8               18 +         2850000

In [166]:
neftlix.groupby("Tür").count()

Yönetmen  Film Adı  Yıl  Süre  Yetişkinlik Düzeyi  \
Tür                                                                        
Aile                          1         1    1     1                   1   
Aksiyon ve Macera             1         1    1     1                   1   
Bilim Kurgu                   1         1    1     1                   1   
Gerilim                       1         1    1     1                   1   
Gerilim,Drama                 1         1    1     1                   1   
Kitaplardan uyarlanan         1         1    1     1                   1   
Komedi                        2         2    2     2                   2   
Komedi,Aile                   1         1    1     1                   1   
Romantik Komedi               1         1    1     1                   1   

                       İzlenme Sayısı  
Tür                                    
Aile                                1  
Aksiyon ve Macera                   1  
Bilim Kurgu                         1  
Gerilim                             1  
Gerilim,Drama                       1  
Kitaplardan uyarlanan               1  
Komedi                              2  
Komedi,Aile                         1  
Romantik Komedi                     1

In [173]:
neftlix.groupby("İzlenme Sayısı").min()

Yönetmen                 Film Adı   Yıl         Süre  \
İzlenme Sayısı                                                                  
500000            Davit Yarovesky               Brightburn  2019  1 sa. 30 dk   
657998              Onur Bilgetay           Aykut Enişte 2  2021  1 sa. 58 dk   
780999              Anthony Russo             The Gary Man  2022   2 sa. 9 dk   
850451             Kristoffer Rus  Masal Bitti,Ben Büyüdüm  2022  1 sa. 46 dk   
999451          Alejandro Montiel                     Pıpa  2022   1 sa.56 dk   
1000250               Özgür Bakar                Hep Yek 4  2021  1 sa. 54 dk   
1452888          Carrie Cracknell                     İkna  2022  1 sa. 49 dk   
2850000               Deon Taylor               Çürük Elma  2019  1 sa. 47 dk   
25544870           Chris Williams           Deniz Canavarı  2022  1 sa. 59 dk   
100000000             Daniel Roby       Bir Numaralı Hedef  2020   2 sa. 5 dk   

                                  Tür Yetişkinlik Düzeyi  
İzlenme Sayısı                                            
500000                    Bilim Kurgu               18 +  
657998                         Komedi               13 +  
780999          Kitaplardan uyarlanan               16 +  
850451                    Komedi,Aile                7 +  
999451                  Gerilim,Drama               16 +  
1000250                        Komedi               16 +  
1452888               Romantik Komedi                7 +  
2850000             Aksiyon ve Macera               18 +  
25544870                         Aile                7 +  
100000000                     Gerilim               18 +

In [169]:
neftlix.groupby("Yıl")["İzlenme Sayısı"].sum()

Yıl
2019      3350000
2020    100000000
2021      1658248
2022     29628659
Name: İzlenme Sayısı, dtype: int64

In [1]:
neftlix.groupby("Yıl")["İzlenme Sayısı"].describe()

NameError: name 'neftlix' is not defined